import './project/_favorite-button';
import './project/_open-menu';
import './project/_product-kit';
import './project/_search';
import './project/_sort';
import './project/_interactive';
import './project/_contacts-tabs';
import './project/_share';
import './project/_review-card-more';
